version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: projectsync-db
    environment:
      POSTGRES_DB: projectsync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  db-data:
