spring:
  application:
    name: backend

  # PostgreSQL Database Configuration
  datasource:
    url: postgresql://localhost:5432/projectsync
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    # Connection Pool Properties
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # JPA/Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: dialect=org.hibernate.dialect.PostgreSQLDialect
