spring:
  application:
    name: backend

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/projectsync
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

    # Connection Pool Properties
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # JPA/Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sediq1973@gmail.com          # replace with your Gmail
    password: jalf lelu gdyo rmmb             # use an App Password, not your Gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

frontend:
  verification-url: https://yourfrontend.com/verify   # Replace with your actual deployed React route

